### ISSUE TITLE
Hello, I would like to ask if the OlympicArena leaderboard will be updated? How do we submit our model to the OlympicArena leaderboard?

### ISSUE THREAD

**Issue by Lisi911** [GAIR-NLP/OlympicArena#6]

**Comment by HuangZhen02** [comment]
Thank you for your interest! You can check out the following link for details on how to submit your model to the OlympicArena leaderboard:  https://huggingface.co/spaces/GAIR/OlympicArenaSubmission

**Comment by Lisi911** [comment]
Yes, I have already sent the results to [gair.olympicarena@gmail.com] following the requirements in the link on November 7, 2024. The email subject is "OlympicArena_test_ID_and_results", and the sender is [chaoli39@iflytek.com]. Please check your inbox to confirm receipt.

**Comment by Lisi911** [comment]
I have received your reply, whether the results of my model on the test set can appear on the OlympicArena leaderboard?

**Comment by HuangZhen02** [comment]
Hi, we have added the results from your model to the leaderboard.
